### ISSUE TITLE
Alizer port detection logic improvement

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/alizer#209]
currently alizer is spending a lot time on port detection, especially on huge repos, as found in https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1683797822489049

Alizer should avoid spending more time on reading binary or test files. 

should also provide a way to separate out the port detection logic for a particular context, rather than combining component & port detection together. 
and perhaps provide a way to turn off port look-up during component detection.

**Comment by elsony** [comment]
We may still have the port detection logic together. We just need to have smarter logic on the port detection phase logic. When we do port detection, we already know the type of application and the context root of the component, we can just scan for the specific files of that Dockerfile/Containerfile, application type under the context root instead of trying to scan the entire repo again.

**Comment by thepetk** [comment]
**Target date**: 14 July 2023

As this issue requires a fair amount of updates on the logic of port / component detection I think we should create a proposal. That said, I'll start drafting the doc.
