### ISSUE TITLE
Supporting remote repositories

### ISSUE THREAD

**Issue by maysunfaisal** [redhat-developer/alizer#80]
I was wondering if there is a vision for alizer to support remote repositories?

Instead of suggesting a local path, I could provide a repository link(github, gitlab, etc) and alizer could detect the language and tech used within the repo by using the public apis from git or if its a relatively unknown repo then clone and detect.

**Comment by lstocchi** [comment]
Hey @maysunfaisal, we never discussed about it because alizer was only used by IDE plugins and always worked with local repos, but alizer is here to be used by third tools so if there is a real need for this, I can put it out on the table.

Where would you use this feature? Would you need to only detect languages/framework or also selecting a devfile? Then idk how authentication for gh apis work but i guess the user should give his credentials to be authenticated and to avoid any api limits, right? Or for private repo... and here it comes my concern, i guess it would be good to handle all of this outside alizer or maybe have a lib which could be used here :thinking:

**Comment by thepetk** [comment]
closing in favor of https://github.com/devfile/api/issues/1175
