### ISSUE TITLE
Alizer cannot properly detect ASP .NET project type

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/alizer#83]
I'm using Alizer `recognizer.Analyze` to detect language of devfile dotnet sample project  https://github.com/yangcao77/devfile-sample-dotnet-basic
Alizer tells me it's a nodejs project. Here is the output: 
```
name: JavaScript, Aliases: [js node nodejs], CanBeComponent: true, Frameworks: [], Tools: [], UsageInPercentage: 75 
name: Smalltalk, Aliases: [squeak], CanBeComponent: false, Frameworks: [], Tools: [], UsageInPercentage: 15 
name: C#, Aliases: [csharp], CanBeComponent: true, Frameworks: [net6.0], Tools: [], UsageInPercentage: 15 
name: GCC Machine Description, Aliases: [], CanBeComponent: false, Frameworks: [], Tools: [], UsageInPercentage: 10 
```

There are 2 issues for this output:
1. I include the .NET configuration file `launchSettings.json` in the sample project, Alizer does not take that configuration file. ideally, if that configuration file exist, and no package.json file in project. even JS count is 75%, should this project still being counted as .Net?

2. Alizer seems count the JS files for webpages as Javascript. while them should be counted as html, as what Github does. 
![Screen Shot 2022-05-27 at 10 50 25 AM](https://user-images.githubusercontent.com/22285490/170723796-926dc9f1-75e7-49f1-a9b1-287f3414844c.png)

**Comment by lstocchi** [comment]
After digging a bit in opened PRs i think this has been already handled in https://github.com/redhat-developer/alizer/pull/76/files . @kadel if you can give that a review it would be great :pray: 

@yangcao77 this is how the different commands should work (extracted from that PR)

1)
**analyze** -> just perform an analysis of all files from the root. It just gives an overview of what's inside the root
**component detection** -> it detects components within the root. If there is a component living in the root it will be in first position of the returned list. If you want infos about the languages used by a component you should use the languages field of the component itself. First language in the list is the main one.
**devfile detection** -> tries to detect a component in the root and return a devfile for it. If there is no component, it start looking for some components withing the sub-folders. If there are none, it uses the outcome of analyze.

So the analyze works fine and the output will still be that one. What you need to do is to perform a component detetion and pick the first item which is the main component and the one to be used for creating a devfile. Then the languages list will be ordered accordingly (so C# in first position in your example).

2)
Regarding the file detected by Alizer and GH. They are different because we cut all files which are not considered belonging to a  `programming` language. HTML, for example, is marked as `markup`. I guess the same for `css` and `cshtml`. This is why you see such a difference. 

What we do is to detect a component by using its config file and then perform a static analysis weighted keeping in consideration the config file.

I'll keep doing some testing until Tomas is able to review that PR but hopefully that should fix this issue. You could also try running that one :)

**Comment by lstocchi** [comment]
Closing it as we verified the .net detection worked with the above example. Thanks again for testing it :pray:
